### ISSUE TITLE
Works wonderfully on Windows, giving error in ubuntu server 16.04

### ISSUE THREAD

**Issue by nicholas1robbins** [David-OConnor/scinot#2]
The error is below. Any ideas on this one?

> nick@ubuntuServer:~$ python3
> Python 3.5.2 (default, Nov 23 2017, 16:37:01)
> [GCC 5.4.0 20160609] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import scinot
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/nick/.local/lib/python3.5/site-packages/scinot/__init__.py", line 1, in <module>
>     from .main import format, sciprint, start, end
>   File "/home/nick/.local/lib/python3.5/site-packages/scinot/main.py", line 82
>     return f"{trimmed}"
>                       ^
> SyntaxError: invalid syntax

Thanks much, 
Nick Robbins

**Comment by David-OConnor** [comment]
The issue is that this package is compatible only with Python 3.6+; the SyntaxError is caused by Python 3.5 not supporting f strings, which are used internally.

**Comment by nicholas1robbins** [comment]
Well... That's what I get for trusting apt...

> nick@ubuntuServer:~$ sudo apt-get install python3
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> python3 is already the newest version (3.5.1-3).

Thanks much.

**Comment by David-OConnor** [comment]
I just pushed an update to here and PyPi (v0.0.9) that supports Python3 versions below 3.6.

**Comment by nicholas1robbins** [comment]
Awesome! That was a quick turnaround. 
I will dig more into it later. 

Thanks much.
