### ISSUE TITLE
Format numpy.float/ints as well

### ISSUE THREAD

**Issue by ewengillies** [David-OConnor/scinot#3]
Hey, thanks for the package, its helpful for writing my thesis.

Just  a quick comment (and hopefully quick fix), this throws an error

```python
import numpy

a_float = np.sum(np.arange(10))
print(scinot.format(a_float))
```

this does not

```python
import numpy

a_float = np.sum(np.arange(10))
print(scinot.format(float(a_float)))
```

In the first case, a_float is a np.float32 type.  Perhaps these types can be supported as well?

**Comment by David-OConnor** [comment]
Thanks for the report; fixed, and uploaded to Pypy as v 0.0.11
